;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	Buffer-menu-delete
	delete-horizontal-space
	delete-indentation
	eval-and-replace
	eval-last-sexp
	insert-parentheses
	kill-region
	repeat
	))

(setq mc/cmds-to-run-once
      '(
	ace-jump-done
	ace-jump-mode
	suspend-frame
	))
