;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	Buffer-menu-delete
	completion-at-point
	delete-horizontal-space
	delete-indentation
	ess-indent-or-complete
	ess-smart-S-assign
	ess-smart-comma
	ess-yank
	eval-and-replace
	eval-last-sexp
	forward-sexp
	insert-parentheses
	kill-region
	mark-word
	repeat
	wdired-finish-edit
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	ace-jump-done
	ace-jump-mode
	suspend-frame
	))
